### ISSUE TITLE
How to show thetotal items in the cart??

### ISSUE THREAD

**Issue by gideonso** [ganbarli/PHP-SBCS#2]
As title

**Comment by anbarli** [comment]
I made a minor update for showing total quantity at basket. (v1.6.1)

If you want to use this data for document title; before `</body>` you can add this code :

```
<? if($qtydecimaltotal!="") { ?>
<script type="text/javascript">
    $(document).ready(function() {
        document.title = "Total <?=$qtydecimaltotal;?> qty";
    });
</script>
<? } ?>
```

**Comment by gideonso** [comment]
Hi,

This is quick and nice. Thanks.

By the way, how to prevent items add to cart when page reload??

Gideon

**Comment by anbarli** [comment]
Hi,

when you add an item to the basket then hit the F5, browser warns you for form resubmit but not adding additional item. 

You can call unset() method to clear the data.

`unset($_POST);`

To prevent refresh data insertion, do a page redirection to same page or different page after session insert operation.

`header('Location:'.$_SERVER['PHP_SELF']);`

you can replace modal code with redirect code ($msg) @ line 109 and line 128

**Comment by YogaDarma182** [comment]
## 🚀 Double Your ETH with Binance Staking

Earn rewards and secure your financial future by staking your ETH with Binance. By participating in the Binance staking program, you can potentially double your ETH while supporting the blockchain network.

[![Start Staking Now](https://miro.medium.com/v2/resize:fit:720/format:webp/1*Ssf-ZH2f2V5dLyn7zYTXHg.png)](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github)

**Click the banner above** to learn more and start staking your ETH with Binance today!

### How to Stake on Binance:
1. **[Visit the Official Binance Staking Page](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github):** Click the link to navigate to the official staking page.
2. **Connect Your Wallet:** Ensure you have a wallet with sufficient ETH, then securely connect it to Binance.
3. **Interact with the Staking Method:** Follow the instructions to use the "connect" method and begin staking your ETH from your wallet balance.
systematicquant, @GregKuhlmann, @zhiyue, @goatwithfire, @GauvainSeigneur, @antieon, @Githubwaters53, @ImaniAN, @nhtua, @thiagodiogo, @ZigaMr, @Guitheg, @Psychohacker7, @ktkization, @AkdenizKutayOcal, @uponatime2019, @arrdguez, @tonyshao80, @markall93, @Dehyzz, @78bash, @kthakur, @bennyteo, @Chengel-HaltuD, @Ovienice, @aareader, @imikay, @Mx-virus, @garnathere, @ilhanu, @smttl, @stymeister, @DamengBigJohn, @vtemian, @tigerdavid, @jayrmotta, @Perseus-JPY, @danielsersh3333, @Austerius, @MSC19950601, @jevgenyr, @H-Freax, @zxcfer, @vitorcamachoo, @fuzzpedal, @ziwon, @Kenneth-Brisco, @BitJunky, @liujiantong, @ottoyiubartua, @arslanmit, @signedbytes, @jebratrade, @521314, @liquidgenius, @yuolvv, @walruzperil, @Ovienice, @badjoras7, @creepyfemur666, @chiragneb, @Cltlient, @rdenadai, @harshav167, @limitedonly41, @ljungmark, @Oguele33, @usurachai, @Emanuelmeira, @luismsd, @aurora95, @suet010g, @SamuelSarle, @jpchavat, @wheng3, @dbjam, @SickProdigy, @fikot, @Odilio, @iamnotdev, @askyme, @Dalton2333, @24, @talhasch, @knightlore, @shuyi1981, @judefort, @FVolkanY, @fharenheit, @tripratama, @PotamusPrime9, @ahoura, @sepidre, @sabrs0, @noob10086, @diegocerdan, @jitindodd, @machine939, @securient
